# Hand landmarks indices configuration
hand_landmarks:
  thumb: [1, 2, 3, 4]
  indexFinger: [5, 6, 7, 8]
  middleFinger: [9, 10, 11, 12]
  ringFinger: [13, 14, 15, 16]
  pinky: [17, 18, 19, 20]
  palmBase: [0]
  max_hands: 2
  num_landmarks: 21
  num_coords: 3

# File paths for raw data storage
paths:
  raw_data: "data/raw/"
  processed: "data/processed/"
  dataset: "data/dataset/"
  labels: "data/labels.csv"
  mapping: "data/label-idx-mapping.json"

# Extraction settings
crops:
  crop_size: [224, 224] # Width, height in pixels
  crop_margin: 40 # Margin around the hand in the crop
  

