train:
  batch_size: 4
  num_epochs: 50
  learning_rate: 1e-3
  weight_decay: 1e-5
  patience: 10
  num_workers: 4

checkpoint:
  save_dir: "models/checkpoints/"
  save_freq: 1
  load: False
  load_dir: "models/checkpoints/"
  load_epoch: 0